repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0  # Replace with latest from https://github.com/psf/black/releases
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=120]  # Optional: adjust line length 