[pytest]
testpaths = .
pythonpath = .
addopts = --retries=1  --image-snapshot-save-diff
markers =
    graphql: mark a test as a graphql scenario
    webapi: mark a test as a webapi scenario
    e2e: mark a test as an end-to-end scenario
    ignore: mark a test as ignored
