[pytest]
testpaths = .
pythonpath = .
addopts = --retries=1 --image-snapshot-save-diff --alluredir=allure-results --clean-alluredir
markers =
    graphql: mark a test as a graphql scenario
    webapi: mark a test as a webapi scenario
    e2e: mark a test as an end-to-end scenario
    ignore: mark a test as ignored
    checkout_mode(mode): test requires specific checkout mode (single-page or multi-step)
    quantity_control(type): test requires specific quantity control (stepper or button)
    range_filter(type): test requires specific range filter type (slider or default)
