from pydantic import BaseModel


class Mutations(BaseModel):
    def __init__(self):
        from graphql_client.types.quote_type import QuoteType
        from graphql_client.types.customer_review import CustomerReview
        from graphql_client.types.member_type import MemberType
        from graphql_client.types.contact_type import ContactType
        from graphql_client.types.cart_type import CartType
        from graphql_client.types.request_registration_type import RequestRegistrationType
        from graphql_client.types.bulk_cart_type import BulkCartType
        from graphql_client.types.identity_result_type import IdentityResultType
        from graphql_client.types.configuration_line_item_type import ConfigurationLineItemType
        from graphql_client.types.bulk_wishlist_type import BulkWishlistType
        from graphql_client.types.customer_order_type import CustomerOrderType
        from graphql_client.types.approve_quote_result_type import ApproveQuoteResultType
        from graphql_client.types.wishlist_type import WishlistType
        from graphql_client.types.work_task_type import WorkTaskType
        from graphql_client.types.custom_identity_result_type import CustomIdentityResultType
        from graphql_client.types.create_review_result import CreateReviewResult
        from graphql_client.types.change_organization_logo_result_type import ChangeOrganizationLogoResultType
        from graphql_client.types.back_in_stock_subscription_type import BackInStockSubscriptionType
        from graphql_client.types.initialize_payment_result_type import InitializePaymentResultType
        from graphql_client.types.organization import Organization
        from graphql_client.types.authorize_payment_result_type import AuthorizePaymentResultType

        self.deleteFile: bool | None
        self.addItem: CartType | None
        self.addGiftItems: CartType | None
        self.rejectGiftItems: CartType | None
        self.clearCart: CartType | None
        self.changeComment: CartType | None
        self.changeCartItemPrice: CartType | None
        self.changeCartItemQuantity: CartType | None
        self.changeCartItemsQuantity: CartType | None
        self.changeCartConfiguredItem: CartType | None
        self.changeCartItemComment: CartType | None
        self.changeCartItemSelected: CartType | None
        self.selectCartItems: CartType | None
        self.unSelectCartItems: CartType | None
        self.selectAllCartItems: CartType | None
        self.unSelectAllCartItems: CartType | None
        self.removeCartItem: CartType | None
        self.removeCartItems: CartType | None
        self.addCoupon: CartType | None
        self.removeCoupon: CartType | None
        self.removeShipment: CartType | None
        self.addOrUpdateCartShipment: CartType | None
        self.addOrUpdateCartPayment: CartType | None
        self.mergeCart: CartType | None
        self.changeCartCurrency: CartType | None
        self.removeCart: bool | None
        self.clearShipments: CartType | None
        self.clearPayments: CartType | None
        self.addOrUpdateCartAddress: CartType | None
        self.removeCartAddress: CartType | None
        self.addItemsCart: CartType | None
        self.addBulkItemsCart: BulkCartType | None
        self.addCartAddress: CartType | None
        self.updateCartDynamicProperties: CartType | None
        self.updateCartItemDynamicProperties: CartType | None
        self.updateCartPaymentDynamicProperties: CartType | None
        self.updateCartShipmentDynamicProperties: CartType | None
        self.changePurchaseOrderNumber: CartType | None
        self.refreshCart: CartType | None
        self.createWishlist: WishlistType | None
        self.cloneWishlist: WishlistType | None
        self.changeWishlist: WishlistType | None
        self.removeWishlist: bool | None
        self.addWishlistItem: WishlistType | None
        self.updateWishListItems: WishlistType | None
        self.addWishlistBulkItem: BulkWishlistType | None
        self.addWishlistItems: WishlistType | None
        self.removeWishlistItem: WishlistType | None
        self.removeWishlistItems: WishlistType | None
        self.moveWishlistItem: WishlistType | None
        self.createConfiguredLineItem: ConfigurationLineItemType | None
        self.createOrderFromCart: CustomerOrderType | None
        self.changeOrderStatus: bool | None
        self.initializePayment: InitializePaymentResultType | None
        self.authorizePayment: AuthorizePaymentResultType | None
        self.updateOrderDynamicProperties: CustomerOrderType | None
        self.updateOrderItemDynamicProperties: CustomerOrderType | None
        self.updateOrderPaymentDynamicProperties: CustomerOrderType | None
        self.updateOrderShipmentDynamicProperties: CustomerOrderType | None
        self.addOrUpdateOrderPayment: CustomerOrderType | None
        self.updateMemberAddresses: MemberType | None
        self.deleteMemberAddresses: MemberType | None
        self.updateOrganization: Organization | None
        self.createOrganization: Organization | None
        self.removeMemberFromOrganization: ContactType | None
        self.requestRegistration: RequestRegistrationType | None
        self.createContact: ContactType | None
        self.updateContact: ContactType | None
        self.deleteContact: bool | None
        self.updatePersonalData: IdentityResultType | None
        self.updateMemberDynamicProperties: MemberType | None
        self.sendVerifyEmail: bool | None
        self.confirmEmail: CustomIdentityResultType | None
        self.resetPasswordByToken: CustomIdentityResultType | None
        self.changePassword: CustomIdentityResultType | None
        self.lockOrganizationContact: ContactType | None
        self.unlockOrganizationContact: ContactType | None
        self.inviteUser: CustomIdentityResultType | None
        self.registerByInvitation: CustomIdentityResultType | None
        self.createUser: IdentityResultType | None
        self.updateUser: IdentityResultType | None
        self.changeOrganizationContactRole: CustomIdentityResultType | None
        self.deleteUsers: IdentityResultType | None
        self.updateRole: IdentityResultType | None
        self.addAddressToFavorites: bool | None
        self.removeAddressFromFavorites: bool | None
        self.pushHistoricalEvent: bool | None
        self.confirmTask: WorkTaskType | None
        self.rejectTask: WorkTaskType | None
        self.deleteSkyflowCard: bool | None
        self.changeOrganizationLogo: ChangeOrganizationLogoResultType | None
        self.addQuoteAttachments: QuoteType | None
        self.addQuoteItems: QuoteType | None
        self.approveQuoteRequest: ApproveQuoteResultType | None
        self.cancelQuoteRequest: QuoteType | None
        self.changeQuoteComment: QuoteType | None
        self.changeQuoteItemQuantity: QuoteType | None
        self.createQuote: QuoteType | None
        self.createQuoteFromCart: QuoteType | None
        self.declineQuoteRequest: QuoteType | None
        self.deleteQuoteAttachments: QuoteType | None
        self.removeQuoteItem: QuoteType | None
        self.submitQuoteRequest: QuoteType | None
        self.updateQuoteAddresses: QuoteType | None
        self.updateQuoteAttachments: QuoteType | None
        self.updateQuoteDynamicProperties: QuoteType | None
        self.addFcmToken: bool | None
        self.clearAllPushMessages: bool | None
        self.deleteFcmToken: bool | None
        self.markAllPushMessagesRead: bool | None
        self.markAllPushMessagesUnread: bool | None
        self.markPushMessageRead: bool | None
        self.markPushMessageUnread: bool | None
        self.activateBackInStockSubscription: BackInStockSubscriptionType | None
        self.deactivateBackInStockSubscription: BackInStockSubscriptionType | None
        self.createCustomerReview: CustomerReview | None
        self.createReview: CreateReviewResult | None
