from pydantic import BaseModel


class Query(BaseModel):
    def __init__(self):
        from graphql_client.types.dynamic_property_connection import DynamicPropertyConnection
        from graphql_client.types.dynamic_property_type import DynamicPropertyType
        from graphql_client.types.configuration_query_response_type import ConfigurationQueryResponseType
        from graphql_client.types.page_connection import PageConnection
        from graphql_client.types.pickup_location_connection import PickupLocationConnection
        from graphql_client.types.page_document_connection import PageDocumentConnection
        from graphql_client.types.product_connection import ProductConnection
        from graphql_client.types.page_document_type import PageDocumentType
        from graphql_client.types.brand_connection import BrandConnection
        from graphql_client.types.prices_sum_type import PricesSumType
        from graphql_client.types.vendor import Vendor
        from graphql_client.types.fulfillment_center_type import FulfillmentCenterType
        from graphql_client.types.product_suggestions_query_response_type import ProductSuggestionsQueryResponseType
        from graphql_client.types.brand_type import BrandType
        from graphql_client.types.file_upload_scope_options_type import FileUploadScopeOptionsType
        from graphql_client.types.page_type import PageType
        from graphql_client.types.store_response_type import StoreResponseType
        from graphql_client.types.organization import Organization
        from graphql_client.types.contact_type import ContactType
        from graphql_client.types.property import Property
        from graphql_client.types.user_type import UserType
        from graphql_client.types.slug_info_response_type import SlugInfoResponseType
        from graphql_client.types.cart_connection import CartConnection
        from graphql_client.types.payment_in_connection import PaymentInConnection
        from graphql_client.types.organization_connection import OrganizationConnection
        from graphql_client.types.cart_type import CartType
        from graphql_client.types.role_type import RoleType
        from graphql_client.types.custom_identity_result_type import CustomIdentityResultType
        from graphql_client.types.child_categories_query_response_type import ChildCategoriesQueryResponseType
        from graphql_client.types.country_region_type import CountryRegionType
        from graphql_client.types.customer_order_connection import CustomerOrderConnection
        from graphql_client.types.configuration_items_response_type import ConfigurationItemsResponseType
        from graphql_client.types.category_connection import CategoryConnection
        from graphql_client.types.property_connection import PropertyConnection
        from graphql_client.types.product import Product
        from graphql_client.types.wishlist_connection import WishlistConnection
        from graphql_client.types.country_type import CountryType
        from graphql_client.types.customer_order_type import CustomerOrderType
        from graphql_client.types.localized_setting_response_type import LocalizedSettingResponseType
        from graphql_client.types.wishlist_type import WishlistType
        from graphql_client.types.contact_connection import ContactConnection
        from graphql_client.types.menu_link_list_type import MenuLinkListType
        from graphql_client.types.fulfillment_center_connection import FulfillmentCenterConnection
        from graphql_client.types.menu_link_list_type import MenuLinkListType
        from graphql_client.types.category import Category

        self.countries: list[CountryType]
        self.regions: list[CountryRegionType]
        self.dynamicProperty: DynamicPropertyType | None
        self.dynamicProperties: DynamicPropertyConnection | None
        self.store: StoreResponseType | None
        self.slugInfo: SlugInfoResponseType | None
        self.product: Product | None
        self.category: Category | None
        self.categories: CategoryConnection | None
        self.properties: PropertyConnection | None
        self.property: Property | None
        self.fulfillmentCenter: FulfillmentCenterType | None
        self.fulfillmentCenters: FulfillmentCenterConnection | None
        self.childCategories: ChildCategoriesQueryResponseType | None
        self.brand: BrandType | None
        self.productSuggestions: ProductSuggestionsQueryResponseType | None
        self.brands: BrandConnection | None
        self.products: ProductConnection | None
        self.fileUploadOptions: FileUploadScopeOptionsType | None
        self.productConfiguration: ConfigurationQueryResponseType | None
        self.validateCoupon: bool | None
        self.wishlist: WishlistType | None
        self.sharedWishlist: WishlistType | None
        self.wishlists: WishlistConnection | None
        self.cart: CartType | None
        self.configurationItems: ConfigurationItemsResponseType | None
        self.pricesSum: PricesSumType | None
        self.getSavedForLater: CartType | None
        self.pickupLocations: PickupLocationConnection | None
        self.carts: CartConnection | None
        self.menu: MenuLinkListType | None
        self.menus: list[MenuLinkListType]
        self.page: PageType | None
        self.pages: PageConnection | None
        self.pageDocument: PageDocumentType | None
        self.pageDocuments: PageDocumentConnection | None
        self.order: CustomerOrderType | None
        self.payments: PaymentInConnection | None
        self.orderLineItemStatuses: LocalizedSettingResponseType | None
        self.orderStatuses: LocalizedSettingResponseType | None
        self.paymentStatuses: LocalizedSettingResponseType | None
        self.orders: CustomerOrderConnection | None
        self.organizationOrders: CustomerOrderConnection | None
        self.shipmentStatuses: LocalizedSettingResponseType | None
        self.me: UserType | None
        self.organization: Organization | None
        self.contact: ContactType | None
        self.vendor: Vendor | None
        self.organizations: OrganizationConnection | None
        self.contacts: ContactConnection | None
        self.checkUsernameUniqueness: bool | None
        self.checkEmailUniqueness: bool | None
        self.requestPasswordReset: bool | None
        self.validatePassword: CustomIdentityResultType | None
        self.user: UserType | None
        self.role: RoleType | None
