class CatalogPageLocators:
    ADD_TO_LIST = "button[title='Add to list']"
    IN_THE_LIST = "button[aria-label='In the list']"
    ACTIVE_HEART = "button[title='In the list']"
    INACTIVE_HEART = "button[title='Add to list']"
    ADD_TO_CART = "button[title='Add to cart']"
    ADD_TO_CART_PDP = "//span[text()='Add to cart']"
    UPDATE_CART = "button[title='Update cart']"
    UPDATE_CART_PDP = "//span[text()='Update cart']"
    PURCHASED_BEFORE_FILTER = "//div[@data-test-id='purchased-before-checkbox-filter']//input"
    PURCHASED_BEFORE_FILTER_TEXT = "//div[@data-test-id='purchased-before-checkbox-filter']//span/span"
