"""Content module — migrated from Katalon `API Coverage/ModuleContent/*`.

Mapping (Katalon script → pytest tests):
  ContentBlog                 → test_blog_full_lifecycle
  ContentMenu                 → test_menu_lifecycle (checkname/create/get/rename/delete)
  ContentNameValidation       → test_folder_create_invalid_name (parametrized)
  ContentPages                → test_pages_full_lifecycle
  ContentTheme                → test_theme_folder_lifecycle
  ContentThemeUpload          → test_theme_zip_upload_and_unpack
  ContentUploadBlacklistCheck → test_upload_forbidden_extension_rejected (parametrized)
"""

import logging
import uuid

import allure
import pytest
import requests

from restapi.operations import CmsContentOperations, MenuLinkOperations

logger = logging.getLogger(__name__)


_FEATURE_PAGES = "Content / Pages (REST API)"
_FEATURE_BLOG = "Content / Blog (REST API)"
_FEATURE_THEME = "Content / Themes (REST API)"
_FEATURE_MENU = "Content / Menu (REST API)"
_FEATURE_VALIDATION = "Content / Validation (REST API)"

_PAGE_FILE_NAME = "qapage.en-US.md"
_PAGE_FILE_BYTES = b"# QA test page\n\nGenerated by automated tests.\n"
_FORBIDDEN_FILE_NAME = "forbidden.exe"
_FORBIDDEN_FILE_BYTES = b"MZ\x00\x00fake exe content"


# -------------------------------------------------------------------- stats


@pytest.mark.restapi
@allure.feature(_FEATURE_PAGES)
@allure.title("Get content stats for store")
def test_content_stats(cms_content_ops: CmsContentOperations, store_id: str) -> None:
    with allure.step(f"GET /api/content/{store_id}/stats"):
        result = cms_content_ops.get_stats(store_id)

    with allure.step("Verify response shape"):
        assert isinstance(result, dict)
        for key in ("pagesCount", "blogsCount", "themesCount"):
            assert key in result, f"Missing {key} in stats: {result}"


# ------------------------------------------------------------------- search


@pytest.mark.restapi
@allure.feature(_FEATURE_PAGES)
@allure.title("Search content pages — basic shape")
def test_content_search_pages(cms_content_ops: CmsContentOperations, store_id: str) -> None:
    with allure.step(f"GET /api/content/pages/{store_id}/search"):
        result = cms_content_ops.search(content_type="pages", store_id=store_id, keyword="")

    with allure.step("Verify response shape"):
        assert isinstance(result, list)


@pytest.mark.restapi
@allure.feature(_FEATURE_THEME)
@allure.title("Search content themes — basic shape")
def test_content_search_themes(cms_content_ops: CmsContentOperations, store_id: str) -> None:
    with allure.step(f"GET /api/content/themes/{store_id}/search"):
        result = cms_content_ops.search(content_type="themes", store_id=store_id, keyword="")

    with allure.step("Verify response shape"):
        assert isinstance(result, list)


# -------------------------------------------------------------- pages flow


@pytest.mark.restapi
@allure.feature(_FEATURE_PAGES)
@allure.title("Pages full lifecycle: folder → upload → search → rename → delete → stats unchanged")
def test_pages_full_lifecycle(cms_content_ops: CmsContentOperations, store_id: str, make_content_folder) -> None:
    content_type = "pages"

    with allure.step("GET initial pages count"):
        initial_pages_count = cms_content_ops.get_stats(store_id)["pagesCount"]

    with allure.step("POST /folder — create folder"):
        folder = make_content_folder(content_type=content_type)
        folder_name = folder["folderName"]

    with allure.step("POST upload file (multipart)"):
        cms_content_ops.upload_file(
            content_type=content_type,
            store_id=store_id,
            folder_url=folder_name,
            file_name=_PAGE_FILE_NAME,
            file_bytes=_PAGE_FILE_BYTES,
            file_content_type="text/markdown",
        )

    # Note: GET ?relativeUrl=... returns the *file content* (text/html) for .md files,
    # not JSON metadata — verifying via /search instead, which is what the Katalon
    # script also does immediately after upload.
    with allure.step("GET /search — locate uploaded file"):
        results = cms_content_ops.search(content_type=content_type, store_id=store_id, keyword=_PAGE_FILE_NAME)
        assert results, f"Uploaded file {_PAGE_FILE_NAME} not in search results"
        assert results[0]["name"] == _PAGE_FILE_NAME

    old_url = results[0]["url"]
    new_file_name = f"renamed-{_PAGE_FILE_NAME}"
    new_url = old_url.replace(_PAGE_FILE_NAME, new_file_name)

    with allure.step("GET /move — rename file"):
        cms_content_ops.move(content_type=content_type, store_id=store_id, old_url=old_url, new_url=new_url)

    with allure.step("GET /search — verify renamed file"):
        renamed = cms_content_ops.search(content_type=content_type, store_id=store_id, keyword=new_file_name)
        assert renamed and renamed[0]["name"] == new_file_name

    with allure.step("DELETE — remove the file"):
        cms_content_ops.delete(
            content_type=content_type,
            store_id=store_id,
            urls=f"/{folder_name}/{new_file_name}",
        )

    with allure.step("GET /search — file should be gone"):
        gone = cms_content_ops.search(content_type=content_type, store_id=store_id, keyword=new_file_name)
        assert not gone or gone[0]["name"] != new_file_name

    # folder cleanup happens in fixture teardown
    with allure.step("Wait for folder cleanup, verify final pages count == initial"):
        # explicit folder delete here so stats compare is meaningful inside the test
        cms_content_ops.delete(content_type=content_type, store_id=store_id, urls=folder_name)
        final_count = cms_content_ops.get_stats(store_id)["pagesCount"]
        assert (
            final_count == initial_pages_count
        ), f"pagesCount drifted: initial={initial_pages_count}, final={final_count}"


# -------------------------------------------------------------- blog flow


@pytest.mark.restapi
@allure.feature(_FEATURE_BLOG)
@allure.title("Blog full lifecycle: folder → post → rename (forbidden + allowed) → delete → 404 → stats unchanged")
def test_blog_full_lifecycle(cms_content_ops: CmsContentOperations, store_id: str, make_content_folder) -> None:
    content_type = "blogs"

    with allure.step("GET initial blogs count"):
        initial_count = cms_content_ops.get_stats(store_id)["blogsCount"]

    with allure.step("POST /folder — create blog folder"):
        folder = make_content_folder(content_type=content_type)
        folder_name = folder["folderName"]

    with allure.step("POST upload blog post (multipart)"):
        cms_content_ops.upload_file(
            content_type=content_type,
            store_id=store_id,
            folder_url=folder_name,
            file_name=_PAGE_FILE_NAME,
            file_bytes=_PAGE_FILE_BYTES,
            file_content_type="text/markdown",
        )

    with allure.step("GET /search — locate post"):
        results = cms_content_ops.search(content_type=content_type, store_id=store_id, keyword=_PAGE_FILE_NAME)
        assert results, "Blog post missing after upload"
        old_url = results[0]["url"]
        relative_url = results[0]["relativeUrl"]

    new_file_name = f"renamed-{_PAGE_FILE_NAME}"
    forbidden_file_name = _PAGE_FILE_NAME.replace(".md", ".exe")
    new_url = old_url.replace(_PAGE_FILE_NAME, new_file_name)
    forbidden_url = old_url.replace(_PAGE_FILE_NAME, forbidden_file_name)

    with allure.step("GET /move to .exe — should fail (forbidden extension)"):
        with pytest.raises(requests.HTTPError) as excinfo:
            cms_content_ops.move(content_type=content_type, store_id=store_id, old_url=old_url, new_url=forbidden_url)
        assert (
            excinfo.value.response.status_code >= 400
        ), f"Expected error rename to .exe, got {excinfo.value.response.status_code}"

    with allure.step("GET /move to .md — should succeed"):
        cms_content_ops.move(content_type=content_type, store_id=store_id, old_url=old_url, new_url=new_url)

    with allure.step("GET /search — find renamed post"):
        renamed = cms_content_ops.search(content_type=content_type, store_id=store_id, keyword=new_file_name)
        assert renamed and renamed[0]["url"] == new_url

    with allure.step("DELETE renamed post"):
        cms_content_ops.delete(content_type=content_type, store_id=store_id, urls=new_url)

    with allure.step("GET via original relative URL — expect 404 / empty"):
        try:
            result = cms_content_ops.get(content_type=content_type, store_id=store_id, relative_url=relative_url)
            assert result is None or not result, f"Deleted post still returned: {result!r}"
        except requests.HTTPError as exc:
            assert exc.response.status_code in (404, 400)

    with allure.step("DELETE folder + verify blogsCount returned to initial"):
        cms_content_ops.delete(content_type=content_type, store_id=store_id, urls=folder_name)
        final_count = cms_content_ops.get_stats(store_id)["blogsCount"]
        assert final_count == initial_count, f"blogsCount drifted: initial={initial_count}, final={final_count}"


# -------------------------------------------------------------- theme flow


@pytest.mark.restapi
@allure.feature(_FEATURE_THEME)
@allure.title("Theme folder lifecycle: create → rename → delete → stats unchanged")
def test_theme_folder_lifecycle(cms_content_ops: CmsContentOperations, store_id: str, make_content_folder) -> None:
    content_type = "themes"

    with allure.step("GET initial themes count"):
        initial_count = cms_content_ops.get_stats(store_id)["themesCount"]

    with allure.step("POST /folder — create theme folder"):
        folder = make_content_folder(content_type=content_type)
        folder_name = folder["folderName"]

    with allure.step("GET /search — locate folder"):
        results = cms_content_ops.search(content_type=content_type, store_id=store_id, keyword=folder_name)
        assert results and results[0]["name"] == folder_name
        old_url = results[0]["url"]
        parent_url = results[0]["parentUrl"]

    new_folder_name = f"{folder_name}Renamed"
    new_url = f"{parent_url}{new_folder_name}"

    with allure.step("GET /move — rename folder"):
        cms_content_ops.move(content_type=content_type, store_id=store_id, old_url=old_url, new_url=new_url)

    with allure.step("GET /search — verify renamed folder"):
        renamed = cms_content_ops.search(content_type=content_type, store_id=store_id, keyword=new_folder_name)
        assert renamed and renamed[0]["name"] == new_folder_name

    with allure.step("DELETE renamed folder + verify themesCount unchanged"):
        cms_content_ops.delete(content_type=content_type, store_id=store_id, urls=new_folder_name)
        final_count = cms_content_ops.get_stats(store_id)["themesCount"]
        assert final_count == initial_count, f"themesCount drifted: initial={initial_count}, final={final_count}"


@pytest.mark.restapi
@allure.feature(_FEATURE_THEME)
@allure.title("Theme zip upload + unpack — verify a file inside the archive is reachable")
@pytest.mark.skip(
    reason=(
        "Requires a real .zip archive with a known internal file. The Katalon test ships "
        "qwetheme_test_x.zip in TestFiles/. Re-enable once an equivalent fixture archive "
        "is added under tests/restapi/content/fixtures/."
    )
)
def test_theme_zip_upload_and_unpack(cms_content_ops: CmsContentOperations, store_id: str) -> None:
    pass


# --------------------------------------------------------------- menu flow


@pytest.mark.restapi
@allure.feature(_FEATURE_MENU)
@allure.title("Get menu link lists for store")
def test_menu_get_all(menu_ops: MenuLinkOperations, store_id: str) -> None:
    with allure.step(f"GET /api/cms/{store_id}/menu"):
        result = menu_ops.get_all(store_id)

    with allure.step("Verify response shape"):
        assert result is None or isinstance(result, list)


@pytest.mark.restapi
@allure.feature(_FEATURE_MENU)
@allure.title(
    "Menu link list lifecycle: checkname-free → create → get-by-id → rename → checkname-taken → delete → gone"
)
@pytest.mark.xfail(
    strict=False,
    reason=(
        "Menu DELETE silently no-ops on this demo backend. Verified empirically: "
        "?ids=<guid> returns 204 but the menu remains in GET /menu; ?listIds=<guid> "
        "(per the .rs file) returns 500 NullReferenceException; ?ids[]= same as ?ids=. "
        "All other lifecycle steps (checkname, create, get-by-id, rename) succeed. "
        "Remove xfail when the backend is fixed."
    ),
)
def test_menu_lifecycle(menu_ops: MenuLinkOperations, store_id: str) -> None:
    initial = menu_ops.get_all(store_id) or []
    initial_count = len(initial)

    list_id = str(uuid.uuid4())
    menu_name = f"QAMenu_{uuid.uuid4().hex[:6]}"
    new_menu_name = f"{menu_name}Renamed"

    try:
        with allure.step(f"GET /checkname?name={menu_name} — expect free"):
            check = menu_ops.checkname(store_id=store_id, name=menu_name)
            assert check.get("result") is True, f"Expected name {menu_name} to be free, got {check}"

        with allure.step("POST — create menu list"):
            menu_ops.create_or_update(
                store_id=store_id,
                list_id=list_id,
                name=menu_name,
                menu_links=[
                    {"priority": 10, "title": "QweLinkTitle", "url": "~/pages/about_us"},
                    {"priority": 0, "title": "QweLinkTitle 2", "url": "~/pages"},
                ],
            )

        with allure.step("GET — created menu appears in list"):
            after_create = menu_ops.get_all(store_id) or []
            assert any(m.get("id") == list_id for m in after_create), "Created list missing"

        with allure.step("GET /{listId} — fetch by id"):
            by_id = menu_ops.get_by_id(store_id=store_id, list_id=list_id)
            assert by_id and by_id["name"] == menu_name

        with allure.step("POST — rename menu"):
            menu_ops.create_or_update(store_id=store_id, list_id=list_id, name=new_menu_name, menu_links=[])

        with allure.step(f"GET /checkname?name={new_menu_name} — expect taken"):
            check2 = menu_ops.checkname(store_id=store_id, name=new_menu_name)
            assert check2.get("result") is False, f"Expected name {new_menu_name} to be taken, got {check2}"

    finally:
        with allure.step("DELETE — remove menu list"):
            try:
                menu_ops.delete(store_id=store_id, list_ids=list_id)
            except Exception as e:
                logger.warning("Cleanup failed: %s", e)

    # Note: GET /{listId} on this backend returns a shell object after DELETE
    # (menuLinks=None, name preserved) rather than the null body the Katalon script
    # expected. Authoritative check is the list-level count returning to baseline.
    with allure.step("Verify deleted list is no longer in the list endpoint"):
        final = menu_ops.get_all(store_id) or []
        assert not any(
            m.get("id") == list_id for m in final
        ), f"Deleted list {list_id} still appears in menu list response"
        assert len(final) == initial_count, f"Menu count drifted: {initial_count} → {len(final)}"


# ----------------------------------------------------------- validation


@pytest.mark.restapi
@allure.feature(_FEATURE_VALIDATION)
@allure.title("Folder name validation: '{folder_name}' must be rejected")
@pytest.mark.parametrize(
    "folder_name",
    [
        pytest.param(" ", id="whitespace-only"),
        pytest.param("/etc/passwd", id="absolute-path"),
        pytest.param("..", id="parent-dir-traversal"),
        pytest.param("a" * 300, id="too-long"),
    ],
)
def test_folder_create_invalid_name(cms_content_ops: CmsContentOperations, store_id: str, folder_name: str) -> None:
    with allure.step(f"POST /folder name={folder_name!r} — expect rejection"):
        try:
            response = cms_content_ops.create_folder(content_type="pages", store_id=store_id, folder_name=folder_name)
        except requests.HTTPError as exc:
            assert exc.response.status_code >= 400
            return
        # If server returned 200 with an error body, it should at least contain a 'message'
        assert isinstance(response, dict), f"Unexpected non-error response: {response!r}"
        assert response.get("message") or response.get(
            "error"
        ), f"Server accepted invalid folder name {folder_name!r}: {response!r}"
        # cleanup if accepted
        try:
            cms_content_ops.delete(content_type="pages", store_id=store_id, urls=folder_name)
        except Exception as e:
            logger.warning("Cleanup failed: %s", e)


# --------------------------------------------------------- blacklist check


@pytest.mark.restapi
@pytest.mark.serial
@allure.feature(_FEATURE_VALIDATION)
@allure.title("Forbidden extension upload rejected for content_type={content_type}")
@pytest.mark.parametrize("content_type", ["pages", "blogs", "themes"])
def test_upload_forbidden_extension_rejected(
    cms_content_ops: CmsContentOperations,
    store_id: str,
    content_type: str,
    ensure_exe_in_blacklist,
    make_content_folder,
) -> None:
    folder = make_content_folder(content_type=content_type)
    folder_name = folder["folderName"]

    with allure.step(f"POST upload {_FORBIDDEN_FILE_NAME} into {content_type}/{folder_name} — expect 4xx/5xx"):
        with pytest.raises(requests.HTTPError) as excinfo:
            cms_content_ops.upload_file(
                content_type=content_type,
                store_id=store_id,
                folder_url=folder_name,
                file_name=_FORBIDDEN_FILE_NAME,
                file_bytes=_FORBIDDEN_FILE_BYTES,
            )

    with allure.step("Verify rejection status code"):
        assert (
            excinfo.value.response.status_code >= 400
        ), f"Expected upload rejection, got {excinfo.value.response.status_code}"
