name: E2E Tests Docker

on:
  workflow_dispatch:
    inputs:
      frontendZipUrl:
        description: 'Frontend zip url'
        required: true
        type: string
        default: 'latest'

jobs:
  e2e-tests:
    uses: VirtoCommerce/.github/.github/workflows/pytest-tests.yml@VCST-4958
    with:
      installModules: 'false'
      installCustomModule: 'false'
      vctestingRepoBranch: '${{ github.ref_name }}'
      frontendZipUrl: '${{ inputs.frontendZipUrl }}'
      customPackagesJsonUrl: 'https://github.com/${{ github.repository }}/raw/${{ github.ref_name }}/backend-packages.json'
      testSuites: 'restapi,e2e'
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}
      testSecretEnvFile: ${{ secrets.VC_TESTING_MODULE_ENV_FILE_NEW }} #${{ secrets.VC_TESTING_MODULE_ENV_FILE }}
      sendgridApiKey: ${{ secrets.SENDGRID_APIKEY_4E2E_AUTOTESTS }}