name: E2E Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox] #chromium, firefox

    env:
      FRONTEND_BASE_URL: https://vcst-qa-storefront.govirto.com
      BACKEND_BASE_URL: https://vcst-qa.govirto.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: Password3
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      USER_EMAIL: b2badmin@test.com
      FRONT_ADMIN: e2e-admin@test.com
      PASSWORD: Password1
      API_KEY: ${{ secrets.API_KEY }}
      STORE_ID: B2B-store
      PLAYWRIGHT_HEADLESS: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Install Playwright Browsers
        run: playwright install --with-deps ${{ matrix.browser }}

      - name: Run E2E Tests
        run: |
          echo "Running E2E tests against ${{ env.BASE_URL }}"
          pytest e2e/ --browser ${{ matrix.browser }} --html=e2e-report.html --self-contained-html --tracing=retain-on-failure -v -s
          pytest tests_e2e/tests/ --browser ${{ matrix.browser }} --html=e2e-report.html --self-contained-html --tracing=retain-on-failure -v -s

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ matrix.browser }}
          path: |
            e2e-report.html
            playwright-report/
            test-results/
          retention-days: 30
